# -*- coding: utf-8 -*-
from flask import *
import random
import json
import re

app = Blueprint('substitution', __name__)

abc = u"ABCČDEFGHIJKLMNOPQRSŠTUVWXYZŽ"
easy = [u"Med prvimi je zamisel o atomu razvil grški filozof Demokrit. Nekoč je sedel na kamnu ob morski obali, držal v roki jabolko in takole razmišljal, da če razreže jabolko na polovico, dobi pol jabolka, če nadaljuje s polovico, dobi četrtino in tako naprej. Vprašal se je, ali lahko režemo tako kar naprej. Demokrit je iz tega razmišljanja povzel, da je število delitev omejeno. Po določenem številu deljenj bi dobili delec, ki ga ne moremo deliti naprej. Ta delec je imenoval atom.",
        u"Pascal velja za enega največjih neuresničenih talentov v zgodovini matematike. Na žalost se  velikokrat ni ukvarjati z matematiko zaradi težav z zdravjem. Že kot otrok je bil Pascal velikokrat bolan. V šolo kasneje prav zaradi svojega krhkega zdravja ni hodil, pač pa je imel domačega učitelja. Njegov oče se je namreč bal, da bi se njegov sin zaradi učenja v šoli preveč izčrpal. Domačemu učitelju je celo naročil, naj da dečku predvsem dobro humanistično izobrazbo s poudarkom na latinskem in grškem jeziku, izogiba pa se naj zahtevne matematike.",
        u"Malo je ljudi v zgodovini znanosti in tehnike, ki bi toliko prispevali k splošnemu napredku človeštva kot prav Nikola Tesla. Že kot majhen otrok, si je dobro zapomnil stvari. To naj bi podedoval po materi. Zelo zgodaj je malega Nikola zanimala narava. Po opazovanju narave se je lotil tudi prvih poskusov. Še preden je bil star pet let, je skušal leteti kot ptič. Njegov polet se je končal s hudim pretresom možganov.",
        u"Ko je Nikola Tesla bil star devetnajst let, je začel študirati elektrotehniko. Pri študiju je bil zelo priden in tako zelo zagnan, da je dekan fakultete celo pisal njegovemu očetu, da naj sina vzame iz šole , ker študij škodljivo vpliva na njegovo zdravje. Očetu je moral obljubiti, da se bo tudi kaj zabaval. Začel je igrati karte. Zaradi sposobnosti kombinatornega mišljenja je večinoma dobival. Denar pa je na koncu vedno vračal tistim, ki so ga izgubili.",
        u"William Herschel se je zapisal v zgodovino astronomije kot konstruktor\ndaljnogledov, kot neumoren opazovalec neba, prvi raziskovalec Rimske ceste in drugih galaksij. Kot mladenič je iz rodne Nemčije pobegnil v Anglijo. V začetku je bil godbenik, komponist in učitelj glasbe, kasneje pa je spremenil poklic in postal eden največjih astronomov. Bil je samouk v glasbi in v astronomiji. Gradil je vse večje daljnoglede, ki jih je pošiljal na vse strani.",
        u"Kopernik je s svojim delom močno vplival na vso znanost in spremenil človekov pogled na svet. Živel in ustvarjal je na prehodu iz srednjega veka v novi vek, ko so fevdalno družbo pretresali pomembni dogodki. Znanje astronomije je bilo nujno potrebno pri trgovanju na dolgih morskih poteh. Misel o okrogli Zemlji je postajala splošno znana. Vsemu temu je sledila še  nova predstava o zgradbi vesolja. Do Kopernika so mislili, da je Zemlja nepremična, da leži v središču vesoljstva in da se vse zvezde, planeti, Sonce in Luna gibljejo okoli nje.",
        u"Rodil se je v revni kmečki družini v zasavskem hribovju. Kot matematika ga najbolj poznamo kot avtorja njegovih logaritmov, s katerimi so računali po svetu v znanosti, šolstvu in vsakdanjem življenju vse do množične uporabe elektronskih računalnikov. Kot profesor matematike na šoli je napisal matematična in fizikalna učbenika. Čeprav je Vega s svojimi logaritmi zaslovel predvsem kot matematik, je bil večji del njegovih razprav in učbenikov posvečenih fiziki. Njegova dela v fiziki zajemajo vsa področja mehanike, predvsem teorijo gravitacije in z njo povezano astronomijo.",
        u"Ideje o dveh gibanjih Zemlje, o vrtenju okoli njene osi in kroženju okoli Sonca, so izrekli že nekateri filozofi starega veka. Te misli so utonile v pozabo. Povzel jih je Kopernik, ki je postavil Sonce v središče našega planetnega sistema, Zemljo pa premaknil v vrsto planetov, ki se gibljejo okoli Sonca. Kopernikov nauk je pomenil prelom s številnimi tradicijami in dotedanjim svetovnim nazorom. Ves srednjeveški svet se je naslanjal na nespremenljivost obstoječega reda. Le drzni ljudje so si upali izreči misel o gibanju Zemlje.",
        u"William Herschel se je zapisal v zgodovino astronomije kot konstruktor daljnogledov, kot neumoren opazovalec neba, prvi raziskovalec Rimske ceste in drugih galaksij. Kot mladenič je iz rodne Nemčije pobegnil v Anglijo. V začetku je bil godbenik, komponist in učitelj glasbe, kasneje pa je spremenil poklic in postal eden največjih astronomov. Bil je samouk v glasbi in v astronomiji. Gradil je vse večje daljnoglede, ki jih je pošiljal na vse strani.",
        u"Kolmogorov se je ukvarjal s širokim poljem matematike. Opredelil je matematične osnove verjetnostne teorije in algoritmične teorije naključnosti ter prispeval ključne prispevke k osnovam statistčne mehanike, stohastičnih procesov, teorije informacije, mehanike tekočin in nelinearne dinamike. Vsa ta področja in njihovi odnosi so osnova za kompleksne sisteme, kot jih danes preučujejo.",
        u"S svojimi daljnogledi je štirikrat skrbno pregledal vse nebo, ki ga je lahko videl iz Anglije. Pri tem je našel nov planet Uran. Glavne raziskave je posvetil zvezdam. S svojimi daljnogledi je lahko prodrl globoko v vesolje. Pri tem je ugotovil, da Osončje ne miruje.",
        u"V vsakdanjem življenju imenujemo paradoks nekaj, kar je sicer resnično, pa vendar v nasprotju z našimi predstavami in izkušnjami. Sklepanje iz navidezno pravilnih dejstev, ki nas privedejo do nesmiselnega rezultata, ravno tako imenujemo paradoks.",
        u"Kako znan je bil ta priimek v svetu, pripoveduje naslednji dogodek. Ko je moral nekoč Herschel na meji pokazati potni list, je carinik začuden vzkliknil: \"Herschel, to vendar ni priimek, to je zvezda!\""]
medium = [  u"KADAR SLEDITE SVOJI SREČI SE VAM BODO ODPRLA VRATA TAM, KODER STE MISLILI, DA JIH SPLOH NI; IN KODER TUDI NI VRAT ZA NIKOGAR DRUGEGA.",
            u"Cauchyjevi matematični prispevki so bili briljantni ter so obsegali preko sedemsto člankov. S Cauchyjem se je začela doba moderne analize. V matematiko je vpeljal standarde preciznosti in strogosti, ki so presegli standarde Leibniza in Newtona.",
            u"Cauchy je najprej napisal obravnavo integralov, ki je postala osnova za moderno kompleksno analizo; nato je sledil članek o širjenju valov v tekočinah, za katerega je dobil nagrado francoske akademije; kasneje pa je napisal članek, ki predstavlja osnovo moderne teorije elastičnosti.",
            u"Cauchy je zgodnjo izobrazbo pridobil od svojega očeta, odvetnika in mojstra klasike. Najprej se je vpisal na študij inženirstva, zaradi slabega zdravja pa so mu svetovali, naj se osredotoči na matematiko. Njegova velika dela so se pričela s serijo briljantnih rešitev nekaterih težkih odprtih problemov.",
            u"Fisherjevi zapiski so opredelili statistiko kot posebno področje proučevanja, katerega metode lahko uporabimo v številnih panogah. Sistematiziral je matematično teorijo statistike in izumil številne nove metode. Slučajni primerjalni eksperiment je najbrž njegov največji dosežek.",
            u"Človeka osrečijo njegovi lastni napori, brž ko spozna potrebne prvine za srečo - preproste užitke, določeno mero poguma, nesebičnost, ljubezen do dela in predvsem čisto vest. Zdaj sem prepričana, da sreča niso le prazne sanje.",
            u"Ideje in metode, ki jih danes poznamo pod imenom statistika, so v devetnajstem in dvajsetem stoletju izumili ljudje, ki so se ukvarjali s problemi, pri katerih je bilo potrebno analizirati velike količine podatkov. Astronomija, biologija, družboslovne vede in celo geodezija lahko trdijo, da so igrale pomembno vlogo pri rojstvu statistike.",
            u"Ena izmed indijskih pravljic govori o preprostem fantu, ki je stehtal slona pri eni izmed mnogih preizkušenj, ki jih je moral prestati. Slona je zapeljal na čoln in na eni strani zaznamoval gladino vode. Nato je znosil na čoln toliko kamenja, da se je čoln znova potopil do oznake. Kamenje je seveda stehtal brez težav.",
            u"Po tem, ko se je Pascal prevrnil s konjsko vprego in komaj ostal živ, se je spremenil potek njegovega življenja. Dogodek mu je namreč predstavljal skrivnostno opozorilo, da Bogu ni všeč, da se ukvarja z matematiko. Odločil se je, da se poslej posveti izključno premišljevanju o veri in Bogu. Lotil se je pisanja zagovora krščanstva, a je njegovo delo ostalo nedokončano",
            u"Lagrange je bil sin javnega uslužbenca in se je rodil v Italiji. S šestnajstimi leti je začel študirati matematiko kot samouk in bil pri devetnajstih izbran za profesorja na kraljevski  šoli v Torinu. Naslednje leto je Lagrange poslal Eulerju rešitve nekaterih slavnih problemov, pri tem pa je uporabil nove metode, ki so se kasneje razvile v vejo analize, ki se imenuje analiza variacij."]
hard = easy[:]
ready = [u"DHEFHAHLHS MR ČR QDSZLČZE M NCLHDCF IHEČRF FZPRFZPCDR. HILRTRECE ČR FZPRFZPCUGR HMGHSR SRLČRPGHMPGR PRHLCČR CG ZEAHLCPFCUGR PRHLCČR GZDEČQUGHMPC PRL ILCMIRSZE DEČQUGR ILCMIRSDR D HMGHSZF MPZPCMPUGR FRBZGCDR, MPHBZMPCUGCB ILHJRMHS, PRHLCČR CGOHLFZJCČR, FRBZGCDR PRDHUCG CG GRECGRZLGR TCGZFCDR. SMZ PZ IHTLHUČZ CG GČCBHSC HTGHMC MH HMGHSZ XZ DHFIERDMGR MCMPRFR, DHP ČCB TZGRM ILRQUQČRČH.",
u"S SBZUTXT LGWUYZRWNLT UN MOTITVIGO SVIHYZ ŽINRWNLGW BSN YNHZ, VT RG UN WGŠVZ BTLNW TE GYRWTUN. ŽIT ONX UN YGMNW YZB ŽWGYNO AIGY. RWGBYN IGETSVGBN UN ŽZSBNOTW EBNELGX. S SBZUTXT LGWUYZRWNLT UN WGŠVZ ŽIZLIW RWZHZVZ B BNSZWUN. ŽIT ONX UN ARZOZBTW, LG ZSZYKUN YN XTIAUN.",
u"U UQŽGJŽKFEI ZDUHFEKFT DIEKTFEIL MŽPŽJLGQ KEGŽF, GŽP FE QDAEP PEQKDNKL, MŽ UEKJŽP U KŽQMPLŠFT Y KŽRDID MPEJQŠŽUŽID DK DYGTRKFŽID. QGHEMŽKFE DY KŽUDJEYKL MPŽUDHKDČ JEFQŠEU, GD KŽQ MPDUEJEFL JL KEQIDQEHKECŽ PEYTHŠŽŠŽ, PŽUKL ŠŽGL DIEKTFEIL MŽPŽJLGQ.",
u"CPCR NAPA ŽU QYE HP BDYYZUC J FJUHI, BDYBRJUTIŽU APFEUTAŽY TRWRTUC. CR ŽU ZRDPE AUCRŠ XUDFSXUE AP ZUŽY BRCPNPHY BRHAY EYFH, ŽU SPDYAYC NPŠITUA JNCEYCAYE: \"XUDFSXUE, HR JUATPD AY BDYYZUC, HR ŽU NJUNTP!\"",
u"AWV CFKŽAŽ DW PSAŽGWN B SIBAJ FSPKŽN YFHEŽ XŽNBPBX VWABEFŽI. RWEBU DW GWVWN RS ESARJ BŠ ABFGEŽ BŠSNŽ, VFQSN K FBEŽ DSŠBNEB ŽR ISEBNW FSPAŽHNDSN, VS UW FSPFWQW DSŠBNEB RS CBNBKŽTB, VBŠŽ CBN DSŠBNES, UW RSVSNDJDW G CBNBKŽTB, VBŠŽ UWIFIŽRB ŽR ISEB RSCFWD. KCFSHSN GW DW, SNŽ NSZEB FWQWAB ISEB ESF RSCFWD. VWABEFŽI DW ŽP IWYS FSPAŽHNDSRDS CBKPWN, VS DW HIWKŽNB VWNŽIWK BAWDWRB. CB VBNBUWRWA HIWKŽNJ VWNDWRD ŠŽ VBŠŽNŽ VWNWT, EŽ YS RW ABFWAB VWNŽIŽ RSCFWD. IS VWNWT DW ŽAWRBKSN SIBA.",
u"ČNCQNT GUTZN LN USUWN SNZGURZYX SUFBUCSYRUSYX ENTUSEOG G LWOŠOGYSY INEUINEYŽU. SN MNTOCE CU  GUTYŽOŽBNE SY FŽGNBZNEY L INEUINEYŽO LNBNŠY EUMNG L LŠBNGZUI. MU ŽOE OEBOŽ ZU PYT ČNCQNT GUTYŽOŽBNE POTNS. G DOTO ŽNCSUZU ČBNG LNBNŠY CGOZUWN ŽBXŽUWN LŠBNGZN SY XOŠYT, ČNR ČN ZU YIUT ŠOINRUWN FRYEUTZN. SZUWOG ORU CU ZU SNIBUR PNT, ŠN PY CU SZUWOG CYS LNBNŠY FRUSZN G DOTY ČBUGUR YLRBČNT. ŠOINRUIF FRYEUTZF ZU QUTO SNBORYT, SNZ ŠN ŠURŽF ČBUŠGCUI ŠOPBO XFINSYCEYRSO YLOPBNLPO C ČOFŠNBŽOI SN TNEYSCŽUI YS WBDŽUI ZULYŽF, YLOWYPN ČN CU SNZ LNXEUGSU INEUINEYŽU.",
u"ŽLZR XQ ZXČPW D ITRPRDWHW IHLHRACW WH CQVHWYQ, YW MW CRZWYR UKWAUQDLZW Y AUZRBHQŽČ HLUKQPYČ OZRDQBCDL YRC UKLD HWYRZL CQAZL. JQ YRC ŽLXVQH RCKRY, AW XQ PRMKR ILURŽHWZ ACDLKW. CR HLX MW URPQPRDLZ UR ŽLCQKW. IQZR ITRPLX XQ ŽLZQTL HWYRZL ILHWŽLZL HLKLDL. UR RULIRDLHXČ HLKLDQ AQ XQ ZRCWZ CČPW UKDWV URAYČARD. BQ UKQPQH XQ MWZ ACLK UQC ZQC, XQ AYČBLZ ZQCQCW YRC UCWO. HXQTRD URZQC AQ XQ YRHOLZ A VČPWŽ UKQCKQARŽ ŽRJTLHRD.",
u"TY ŠM XSTYVG ZMRVG HSV RZGO LMBMZXGŠRZ VMZ, ŠM EGJMV UZALSOGZS MVMTZOYZMQXSTY. ŽOS UZALSŠA ŠM HSV EMVY ŽOSLMX SX ZGTY EMVY EGPXGX, LG ŠM LMTGX NGTAVZMZM IMVY ŽSRGV XŠMPYBMWA YJMZA, LG XGŠ RSXG BEGWM SE UYVM , TMO UZALSŠ UTYLVŠSBY BŽVSBG XG XŠMPYBY ELOGBŠM. YJMZA ŠM WYOGV YHVŠAHSZS, LG RM HY ZALS TGŠ EGHGBGV. EGJMV ŠM SPOGZS TGOZM. EGOGLS RŽYRYHXYRZS TYWHSXGZYOXMPG WSUVŠMXŠG ŠM BMJSXYWG LYHSBGV. LMXGO ŽG ŠM XG TYXIA BMLXY BOGJGV ZSRZSW, TS RY PG SEPAHSVS.",
u"NPSSPČŠ MIXYFMIS YI QI AČVPYČS O ALUHUOPTU ČYŽXUTUŠPQI RUŽ RUTYŽXKRŽUX HČSQTULSIHUO, RUŽ TIKŠUXIT UVČAUOČSIF TIDČ, VXOP XČAPYRUOČSIF XPŠYRI FIYŽI PT HXKLPM LČSČRYPQ. RUŽ ŠSČHITPG QI PA XUHTI TIŠGPQI VUDILTPS O ČTLSPQU. O AČGIŽRK QI DPS LUHDITPR, RUŠVUTPYŽ PT KGPŽISQ LSČYDI, RČYTIQI VČ QI YVXIŠITPS VURSPF PT VUYŽČS IHIT TČQOIGQPM ČYŽXUTUŠUO. DPS QI YČŠUKR O LSČYDP PT O ČYŽXUTUŠPQP. LXČHPS QI OYI OIGQI HČSQTULSIHI, RP QPM QI VUZPSQČS TČ OYI YŽXČTP.",
u"ČGHMKFBČ CM L LTGCBE OMDGE EGPFG THDBTZD FZ TLG XFZFGLR BF LHKMEMFBD PDGTMČGT HGNDMO FZ LTMR. YBTMD BF ŠLRTZKCZD CM FZ HKMAGOŠ BX LKMOFCMNZ TMČZ T FGTB TMČ, ČG LG IMTOZDFG OKŠYŽG HKMRKMLZDB HGEMEŽFB OGNGOČB. XFZFCM ZLRKGFGEBCM CM ŽBDG FŠCFG HGRKMŽFG HKB RKNGTZFCŠ FZ OGDNBA EGKLČBA HGRMA. EBLMD G GČKGNDB XMEDCB CM HGLRZCZDZ LHDGQFG XFZFZ. TLMEŠ RMEŠ CM LDMOBDZ QM  FGTZ HKMOLRZTZ G XNKZOŽB TMLGDCZ. OG ČGHMKFBČZ LG EBLDBDB, OZ CM XMEDCZ FMHKMEBPFZ, OZ DMYB T LKMOBQPŠ TMLGDCLRTZ BF OZ LM TLM XTMXOM, HDZFMRB, LGFSM BF DŠFZ NBŽDCMCG GČGDB FCM.",
u"AYX ČELRAR UY PSARFYK C SICAJ ESPLRK ŽEGŠR ZRKCPCZ XYACŠERI. BYŠCW UY FYXYK BS ŠSABJ CT ACEFŠR CTSKR, XEQSK L ECŠR USTCKŠC RB ISŠCKY ESPARGKUSK, XS WY ESPEYQY USTCKŠC BS ČCKCLRVC, XCTR ČCK USTCKŠS, WY BSXSKUJUY F ČCKCLRVC, XCTR WYIEIRBC RB ISŠC BSČEYU. LČESGSK FY UY, SKR KSHŠC EYQYAC ISŠC ŠSE BSČEYU. XYACŠERI UY RP IYŽS ESPARGKUSBUS ČCLPYK, XS UY GIYLRKC XYKRIYL CAYUYBC. ČC XCKCWYBYA GIYLRKJ XYKUYBU TR XCTRKR XYKYV, ŠR ŽS BY ACEYAC XYKRIR BSČEYU. IS XYKYV UY RAYBCLSK SICA.",
u"JGOAČ MV BV Š JVŠFA CDVLCA OJRYAFA Š XZMZŠMCVD KJAŽGŠBR. CGQ DZQVDZQACZ NZ FZBŽGČB HGXFZDG CGQ ZŠQGJBZ FBVNGŠAK ČGNZJAQDGŠ, M CZQVJADA MG JZLRFZČA HG MŠVQR Š XFZFGMQA, PGČMQŠR AF ŠMZCOZFBVD YAŠČBVFBR ŠMV OG DFGYALFV RHGJZŽV VČVCQJGFMCAK JZLRFZČFACGŠ. CGQ HJGEVMGJ DZQVDZQACV FZ PGČA BV FZHAMZČ DZQVDZQALFZ AF EAXACZČFZ RLŽVFACZ. LVHJZŠ BV ŠVNZ M MŠGBADA ČGNZJAQDA XZMČGŠVČ HJVOŠMVD CGQ DZQVDZQAC, BV ŽAČ ŠVLBA OVČ FBVNGŠAK JZXHJZŠ AF RLŽVFACGŠ HGMŠVLVFAK EAXACA. FBVNGŠZ OVČZ Š EAXACA XZBVDZBG ŠMZ HGOJGLBZ DVKZFACV, HJVOŠMVD QVGJABG NJZŠAQZSABV AF X FBG HGŠVXZFG ZMQJGFGDABG.",
u"YTUZU P THUX WYQNSZYX LUOGZU, P HCEUSZF PŽPGY SZUSU PČY YS ŽCPMUSZF PŽPGY ČPSRN, ČP YLCUŽGY MU SUŽNEUCY VYGPLPVY ČENCUWN HUŽN. EU OYČGY ČP FEPSYGU H APLNQP. APHLUG ZYX ZU ŽPAUCSYŽ, ŽY ZU APČENHYG ČPSRU H ČCUTYDŠU SNDUWN AGNSUESUWN ČYČEUON, LUOGZP AN ACUONŽSYG H HCČEP AGNSUEPH, ŽY ČU WYQGZUZP PŽPGY ČPSRN. ŽPAUCSYŽPH SNFŽ ZU APOUSYG ACUGPO Č DEUHYGSYOY ECNTYRYZNOY YS TPEUTNSZYO ČHUEPHSYO SNLPCPO. HUČ ČCUTSZUHUDŽY ČHUE ČU ZU SNČGNSZNG SN SUČACUOUSGZYHPČE PQČEPZUŠUWN CUTN. GU TCLSY GZFTZU ČP ČY FANGY YLCUŠY OYČUG P WYQNSZF LUOGZU.",
u"HYMMYPI XUBCRXUM CU ZU NPLYCPM G NWETEGYSE PCDBESEIYZU ŽED ŽESCDBFŽDEB TPMZSEWMUTEG, ŽED SUFIEBUS ELPNEGPMUR SUQP, LBGY BPNYCŽEGPMUR BYICŽU RUCDU YS TBFWYX WPMPŽCYZ. ŽED IMPTUSYŠ ZU YN BETSU SUIŠYZU LEQUWSYM G PSWMYZE. G NPŠUDŽF ZU QYM WETQUSYŽ, ŽEILESYCD YS FŠYDUMZ WMPCQU, ŽPCSUZU LP ZU CLBUIUSYM LEŽMYR YS LECDPM UTUS SPZGUŠZYX PCDBESEIEG. QYM ZU CPIEFŽ G WMPCQY YS G PCDBESEIYZY. WBPTYM ZU GCU GUŠZU TPMZSEWMUTU, ŽY ZYX ZU LEČYMZPM SP GCU CDBPSY.",
u"VZWXZSZGZB EQ UQ AVBIGUIW E NTGZVTX ŽZWUQX XIJQXIJTVQ. ZŽGQPQWTW UQ XIJQXIJTMYQ ZEYZBQ BQGUQJYZEJYQ JQZGTUQ TY IWSZGTJXTMYQ JQZGTUQ YIVWUAMYZEJT JQG ŽGTEŽQBIW VWUAMYQ ŽGTEŽQBVQ V ZEYZBIX EJIJTEJMYQ XQŠIYTVQ, EJZŠIEJTMYTŠ ŽGZLQEZB, JQZGTUQ TYRZGXILTUQ, XQŠIYTVQ JQVZMTY TY YQWTYQIGYQ PTYIXTVQ. BEI JI ŽZPGZMUI TY YUTŠZBT ZPYZET EZ ZEYZBI FI VZXŽWQVEYQ ETEJQXQ, VZJ UTŠ PIYQE ŽGQAMAUQUZ.",
u"I IPDEVBV ZUAECDLAŽZV EŽ JMVHVKHUM IKHWCD FHŽLAŽZUA PIŽ CŽWD, KV LU EŽ AUOKD PVZŽA VŠ UCLAVEŽ. FHV MŽB EŽ CUJŽA CDP FAUCŽM NHUC. LAUPCŽ HUŠVIKUPŽ EŽ FDIPŽMVA ŠPŽŠZUB. I IPDEVBV ZUAECDLAŽZV EŽ AUOKD FHDZHA LADWDKD P PŽIDAEŽ. FHV MŽB EŽ NLDMDPVA, ZU DIDCYEŽ CŽ BVHNEŽ.",
u"S SMZDTZGČRF YCSEČRGČQ CFRGQČRFH IZLZTHDM GRDZČ, DZL ČR MCJRL LRMGCUGH, IZ SRGTZL S GZMILHPČQ X GZNCFC ILRTMPZSZFC CG CXDQNGČZFC. MDERIZGČR CX GZSCTRXGH ILZSCEGCB TRČMPRS, DC GZM ILCSRTRČH TH GRMFCMREGRAZ LRXQEPZPZ, LZSGH PZDH CFRGQČRFH IZLZTHDM.",
u"ŠDŠW CVDV RJ EQT ID XZQQUJŠ M ŽMJIS, XZQXWMJHSRJ VDŽTJHVRQ HWLWHJŠ. ŠW RJ UWZDT VJŠWG NJZŽFNJT VD UJRQ XWŠDCDIQ XWIVQ TQŽI, RJ FDZQVQŠ CDGSHJV MCŠTQŠVQT: \"NJZŽFNJT, IW MJVHDZ VQ XZQQUJŠ, IW RJ CMJCHD!\"",
u"CZY FHONCN JZ ŠUCNIZB D ULDCM HUŠONB SHKEN ŽNBDŠDŽ YZCDEHNL. ČZEDX JZ IZYZB ČU EUCČM DV CDHIEN DVUBN, YHTUB O HDEN JUVDBED NČ LUEDBZ HUŠCNKBJUB, YU XZ HUŠHZTZ JUVDBED ČU FDBDONWD, YDVN FDB JUVDBEU, XZ ČUYUBJMJZ I FDBDONWD, YDVN XZLHLNČD NČ LUED ČUFHZJ. OFHUKUB IZ JZ, UBN BUAED HZTZCD LUED EUH ČUFHZJ. YZCDEHNL JZ NŠ LZSU HUŠCNKBJUČJU FDOŠZB, YU JZ KLZONBD YZBNLZO DCZJZČD. FD YDBDXZČZC KLZONBM YZBJZČJ VN YDVNBN YZBZW, EN SU ČZ CDHZCD YZBNLN ČUFHZJ. LU YZBZW JZ NCZČDOUB ULDC.",
u"FŠIUŠR MXRZŠ QŠ XČXŽŠ ČŠZMXVZEC ČXLHXIČEVXČEC KŠRXČKDM M QŽDWDMEČE BŠKXBŠKEAX. ČŠ SŠRDIK IX  MXREADAHŠK ČE LAMŠHZŠKE Q BŠKXBŠKEAD QŠHŠWE KXSŠM Q QWHŠMZXB. SX ADK DKHDA ZX TER FŠIUŠR MXREADAHŠK TDRŠČ. M JDRD AŠIČXZX FHŠM QŠHŠWE IMDZXŽŠ AHCAXŽŠ QWHŠMZŠ ČE CDWER, FŠV FŠ ZX EBXR WDBŠVXŽŠ LVEKXRZŠ. ČZXŽDM DVX IX ZX ČŠBHXV TŠR, WŠ TE IX ČZXŽDM IEČ QŠHŠWE LVXČZŠ M JDRE FHXMXV EQVHFŠR. WDBŠVXBL LVEKXRZL ZX UXRD ČŠHDVER, ČŠZ WŠ WXVAL FHXWMIXB WDTHD CLBŠČEIKEVČD EQDTHŠQTD I FDLWŠHADB ČŠ RŠKEČIAXB EČ ŽHJAXB ZXQEAL, EQDŽETŠ FŠ IX ČŠZ QŠCKXMČX BŠKXBŠKEAX.",
u"GXFI CE FCQDB S VAIDISBHB VHXHIMPB BH PERHBČE, ČB YB PIFBČI JLBMJESXFB Č MJFIOHEGQ HXJLEDČQ ŽFISEOPSX ČIP JLXS HBČIFX PEMFX. WE ČIP GXCREH IPLIČ, MB CE DIYLI VXJIGHBF MPSXLB. PI HXC YB JIDEDISXF JI GXPELB. VEFI VAIDXC CE GXFEAX HBČIFX VXHBGXFX HXLXSX. JI IJXVISXHCQ HXLXSE ME CE FIPBF PQDB JLSBR JIMČQMIS. OE JLEDEH CE YBF MPXL JEP FEP, CE MČQOXF FEPEPB ČIP JPBŽ. HCEAIS JIFEP ME CE ČIHŽXF M RQDBG JLEPLEMIG GIWAXHIS.",
u"OIZLIX ČPXVI GI PŽPSI ŽIVČPMVTŠ ŽPCUPZŽTMPŽTŠ BIXPŽBKČ Č GSKNKČTŽT YIBPYIBTWP. ŽI HIXKZB ZP  ČPXTWKWUIB ŽT CWČIUVIBT G YIBPYIBTWK GIUINT BPHIČ G GNUIČVPY. HP WKB KBUKW VP JTX OIZLIX ČPXTWKWUIB JKXIŽ. Č AKXK WIZŽPVP OUIČ GIUINT ZČKVPSI WUŠWPSI GNUIČVI ŽT ŠKNTX, OIM OI VP TYPX NKYIMPSI CMTBPXVI. ŽVPSKČ KMP ZP VP ŽIYUPM JIX, NI JT ZP ŽVPSKČ ZTŽ GIUINT CMPŽVI Č AKXT OUPČPM TGMUOIX. NKYIMPYC CMTBPXVC VP LPXK ŽIUKMTX, ŽIV NI NPMWC OUPNČZPY NKJUK ŠCYIŽTZBTMŽK TGKJUIGJK Z OKCNIUWKY ŽI XIBTŽZWPY TŽ SUAWPY VPGTWC, TGKSTJI OI ZP ŽIV GIŠBPČŽP YIBPYIBTWP.",
u"EJ DO HCEJFZ QONFZ ŽCF NQZM SOŠOQHZDNQ FOQ, DO XZIOF PQRSCMZQC OFOEQMJQOBHCEJ. KMC PQRSCDR DO ŽCF XOFJ KMCSOH CH QZEJ XOFJ XZAHZH, SZ DO SOEZH ČZERFQOQO TOFJ KCNZF HDOAJŠOGR JIOQR, SZ HZD NCHZ ŠXZGO CX PJFO , EOM PQRSCD PEJSFDCŠJ ŠKFCŠZ HZ HDOAJŠJ XSMZŠDO. JIOQR DO GJMZF JŽFDRŽCQC, SZ NO ŽJ QRSC EZD XZŽZŠZF. XZIOF DO CAMZQC EZMQO. XZMZSC NKJNJŽHJNQC EJGŽCHZQJMHOAZ GCPFDOHDZ DO ŠOICHJGZ SJŽCŠZF. SOHZM KZ DO HZ EJHTR ŠOSHJ ŠMZIZF QCNQCG, EC NJ AZ CXARŽCFC.",
u"SBDDBYE AULMŽAUD MU CU WYIBMYD Q WKGRGQBFG YMOLGFGEBCU ČGO ČGFMOLPČOGL RYDCFGKDURGQ, ČGO FUPEGLUF GIYWGQYDUŽ FUZY, ILQB LYWBMČGQYDUŽ LBEMČU ŽUMOU BF RLPKBA KYDYČMBC. ČGO EDYRUFBH CU BW LGRFU FUEHBCU IGZUKFBD Q YFKDBCG. Q WYHUOČP CU ZBD KGRZUFBČ, ČGEIGFBMO BF PHBOUDC KDYMZU, ČYMFUCU IY CU MILUEUFBD IGČDBŽ BF IGMOYD URUF FYCQUHCBA YMOLGFGEGQ. ZBD CU MYEGPČ Q KDYMZB BF Q YMOLGFGEBCB. KLYRBD CU QMU QUHCU RYDCFGKDURU, ČB CBA CU IGNBDCYD FY QMU MOLYFB.",
u"BEFKHDZB AK I INEAZČ ŽKCEČ ČEYDE NFCZNVC DV NIE ŠDVDEIL ZD IFHKČKDZC YCENKBEN FERCKŽ DV INKL. TZNKC ZD MILNVHAVC AK DV FHKUEŽM ZŠ IHKŽDAKRV NKBV N DENZ NKB, BE IE OKNŽVCDE ŽHMTWE FHKLHKIVCZ FEČKČWDZ ŽEREŽBZ. ŠDVDAK VILHEDEČZAK AK WZCE DMADE FELHKWDE FHZ LHRENVDAM DV ŽECRZU ČEHIBZU FELKU. ČZIKC E EBHERCZ ŠKČCAZ AK FEILVAVCV IFCEJDE ŠDVDV. NIKČM LKČM AK ICKŽZCV JK  DENV FHKŽILVNV E ŠRHVŽWZ NKIECAV. ŽE BEFKHDZBV IE ČZICZCZ, ŽV AK ŠKČCAV DKFHKČZYDV, ŽV CKTZ N IHKŽZJYM NKIECAILNV ZD ŽV IK NIK ŠNKŠŽK, FCVDKLZ, IEDXK ZD CMDV RZWCAKAE EBECZ DAK.",
u"JGŽCČ LK AK R JKRFC BDKZBC ŽJQVCFC R UWLWRLBKD EJCXGRAQ. BGP DWPKDWPCBW NW FWAXGČA HGUFWDG BGP WRPGJAW FAKNGRCE ČGNWJCPDGR, L BWPKJCDC LG JWZQFWČC HG LRKPQ R UFWFGLPC, MGČLPRQ CF RLWBŽWFAKD VCRČAKFAQ RLK ŽG DFGVCZFK QHGJWXK KČKBPJGFLBCE JWZQFWČFCBGR. BGP HJGOKLGJ DWPKDWPCBK FW MGČC AK FWHCLWČ DWPKDWPCZFW CF OCUCBWČFW QZXKFCBW. ZKHJWR AK RKNW L LRGACDC ČGNWJCPDC UWLČGRKČ HJKŽRLKD BGP DWPKDWPCB, AK XCČ RKZAC ŽKČ FAKNGRCE JWUHJWR CF QZXKFCBGR HGLRKZKFCE OCUCBC. FAKNGRW ŽKČW R OCUCBC UWAKDWAG RLW HGŽJGZAW DKEWFCBK, HJKŽRLKD PKGJCAG NJWRCPWYCAK CF U FAG HGRKUWFG WLPJGFGDCAG.",
u"TKLUL Z KALŠ RTGFYUTŠ DLXWUL, Z APILYUN ZVZWT YULYL ZOT TY VPZELYUN ZVZWT OZYHF, OZ TDPLVWT EL YLVFILPT QTWZDZQT OIFPLRF ALVF. IL XTOWT OZ NIZYTWL A ŽZDFGZ. ŽZADLW UTŠ UL VZŽLPYTV, VT UL ŽZOIFATW OZYHL A OPLKTMJL YFMLRF ŽWFYLIYLRF OTOILXF, DLXWUZ ŽF ŽPLXFVYTW A APOIZ ŽWFYLIZA, VT OL RTGWULUZ ZVZWT OZYHF. VZŽLPYTVZA YFNV UL ŽZXLYTW ŽPLWZX O MILATWYTXT IPFKTHTUFXT TY KZILKFYUTX OALIZAYTX YFDZPZX. ALO OPLKYULALMVT OALI OL UL YFOWFYUFW YF YLOŽPLXLYWUTAZOI ZGOIZULJLRF PLKF. WL KPDYT WUNKUL OZ OT NŽFWT TDPLJT XTOLW Z RTGFYUN DLXWUL.",
u"GZLLZPO YUABRYUL BU ŽU JPNZBPL F JXETEFZVE PBČAEVEOZŽU SEČ SEVBČADSČEA TPLŽVEXLUTEF, SEČ VUDOEAUV ENPJEFPLUR VUQP, NAFZ APJZBSEFPLUR AZOBSU RUBČU ZV TADXZY XPLPSBZŽ. SEČ OLPTUVZŠ ŽU ZJ AETVU VUOŠZŽU NEQUXVZL F PVXLZŽE. F JPŠUČSD ŽU QZL XETQUVZS, SEONEVZBČ ZV DŠZČULŽ XLPBQU, SPBVUŽU NP ŽU BNAUOUVZL NESLZR ZV NEBČPL UTUV VPŽFUŠŽZY PBČAEVEOEF. QZL ŽU BPOEDS F XLPBQZ ZV F PBČAEVEOZŽZ. XAPTZL ŽU FBU FUŠŽU TPLŽVEXLUTU, SZ ŽZY ŽU NECZLŽPL VP FBU BČAPVZ.",
u"YOZŽOUOAOE BŠ XŠ DYELAXLZ B CWAOYWŽ SOZXŠŽ ŽLČŠŽLČWYŠ. OSAŠRŠZWZ XŠ ŽLČŠŽLČWQGŠ OBGOEŠ EŠAXŠČGOBČGŠ ČŠOAWXŠ WG LZUOAWČŽWQGŠ ČŠOAWXŠ GLYZXDQGOBČW ČŠA SAWBSŠELZ YZXDQGŠ SAWBSŠEYŠ Y OBGOELŽ BČLČWBČQGŠ ŽŠVLGWYŠ, BČOVLBČWQGWV SAONŠBOE, ČŠOAWXŠ WGTOAŽLNWXŠ, ŽŠVLGWYŠ ČŠYOQWG WG GŠZWGŠLAGŠ RWGLŽWYŠ. EBL ČL SORAOQXL WG GXWVOEW ORGOBW BO OBGOEL JL YOŽSZŠYBGŠ BWBČŠŽŠ, YOČ XWV RLGŠB SAŠDQDXŠXO.",
u"J JPDLECE ZVBLČDIBŽZE LŽ KNEHEAHVN JAHWČD FHŽIBŽZVB PJŽ ČŽWD, AE IV LŽ BVSAD PEZŽB ET VČIBELŽ. FHE NŽC LŽ ČVKŽB ČDP FBVČŽN OHVČ. IBVPČŽ HVTEJAVPŽ LŽ FDJPŽNEB TPŽTZVC. J JPDLECE ZVBLČDIBŽZE LŽ BVSAD FHDZHB IBDWDAD P PŽJDBLŽ. FHE NŽC LŽ OIDNDPEB, ZV DJDČYLŽ ČŽ CEHOLŽ.",
u"G GYCRHCTQIŠ BPGSQITQO PŠITOQIŠU VCXCHURY TIRCQ, RCX QI YPDIX XIYTPFTU, VC GITHCX G TCYVXUŽQO A TCZPŠP VXIHYŽCGCŠP PT PAROZTQCŠP. YRSIVCTQI PA TCGPHIATU VXCGPSTPM HIQYŽIG, RP TCY VXPGIHIQU HU TIYŠPYISTILC XIAOSŽCŽC, XCGTU ŽCRU PŠITOQIŠU VCXCHURY.",
u"XJXČ HŽJŽ WR MUY AJ LVUUZRX C ECRAB, LVULČCRQBWR ŽJEYRQŽWU QČŠČQRX. XČ WR ZČVJY ŽRXČP TRVENTRY ŽJ ZRWU LČXJHJAU LČAŽU YUEA, WR NJVUŽUX HJPBQRŽ CHXYUXŽUY: \"TRVENTRY, AČ CRŽQJV ŽU LVUUZRX, AČ WR HCRHQJ!\"",
u"DWČG AK ČAQŽC R UNGŽGRCFC UFWFGLPC CF PKEFCBK, BC XC PGČCBG HJCLHKRWČC B LHČGMFKDQ FWHJKŽBQ ZČGRKMPRW BGP HJWR FCBGČW PKLČW. VK BGP DWAEKF GPJGB, LC AK ŽGXJG UWHGDFCČ LPRWJC. PG FWA XC HGŽKŽGRWČ HG DWPKJC. UKČG UNGŽWA AK DWČKNW FCBGČW UWFCDWČW FWJWRW. HG GHWUGRWFAQ FWJWRK LK AK ČGPCČ PQŽC HJRCE HGLBQLGR. MK HJKŽKF AK XCČ LPWJ HKP ČKP, AK LBQMWČ ČKPKPC BGP HPCZ. FAKNGR HGČKP LK AK BGFZWČ L EQŽCD HJKPJKLGD DGVNWFGR.",
u"DUJ GIPADA BU VXDAKUČ F XMFDN IXVPAČ RILCA TAČFVFT JUDFCIAM. EUCFŽ BU KUJUČ EX CXDEN FY DFIKCA FYXČA, JIWXČ P IFCA BXYFČCF AE MXCFČU IXVDALČBXČ, JX ŽU IXVIUWU BXYFČCF EX GFČFPAZF, JFYA GFČ BXYFČCX, ŽU EXJXČBNBU K GFČFPAZF, JFYA ŽUMIMAEF AE MXCF EXGIUB. PGIXLXČ KU BU, XČA ČXOCF IUWUDF MXCF CXI EXGIUB. JUDFCIAM BU AV MURX IXVDALČBXEBX GFPVUČ, JX BU LMUPAČF JUČAMUP FDUBUEF. GF JFČFŽUEUD LMUPAČN JUČBUEB YA JFYAČA JUČUZ, CA RX EU DFIUDF JUČAMA EXGIUB. MX JUČUZ BU ADUEFPXČ XMFD.",
u"BRDTRS HWSPR NR WOWYR ORPHWUPŽZ OWGČWDOŽUWOŽZ FRSWOFAH H NYAVAHŽOŽ MRFWMRFŽIW. OR QRSADF DW  HWSŽIAIČRF OŽ GIHRČPRFŽ N MRFWMRFŽIA NRČRVŽ FWQRH N NVČRHPWM. QW IAF AFČAI PW ŠŽS BRDTRS HWSŽIAIČRF ŠASRO. H EASA IRDOWPW BČRH NRČRVŽ DHAPWYR IČZIWYR NVČRHPR OŽ ZAVŽS, BRU BR PW ŽMWS VAMRUWYR GUŽFWSPR. OPWYAH AUW DW PW ORMČWU ŠRS, VR ŠŽ DW OPWYAH DŽO NRČRVŽ GUWOPR H EASŽ BČWHWU ŽNUČBRS. VAMRUWMG GUŽFWSPG PW TWSA ORČAUŽS, ORP VR VWUIG BČWVHDWM VAŠČA ZGMROŽDFŽUOA ŽNAŠČRNŠA D BAGVRČIAM OR SRFŽODIWM ŽO YČEIWM PWNŽIG, ŽNAYŽŠR BR DW ORP NRZFWHOW MRFWMRFŽIW.",
u"VZ UL YTVZWF ILOWF GTW OIFP KLALIYFUOI WLI, UL DFJLW MINKTPFIT LWLVIPZILŠYTVZ. ŽPT MINKTUN UL GTW DLWZ ŽPTKLY TY IFVZ DLWZ DFRYFY, KF UL KLVFY QFVNWILIL HLWZ ŽTOFW YULRZALXN ZJLIN, KF YFU OTYF ADFXL TD MZWL , VLP MINKTU MVZKWUTAZ AŽWTAF YF YULRZAZ DKPFAUL. ZJLIN UL XZPFW ZGWUNGTIT, KF OL GZ INKT VFU DFGFAFW. DFJLW UL TRPFIT VFPIL. DFPFKT OŽZOZGYZOIT VZXGTYFIZPYLRF XTMWULYUF UL ALJTYZXF KZGTAFW. KLYFP ŽF UL YF VZYHN ALKYZ APFJFW ITOITX, VT OZ RF TDRNGTWT.",
u"FYSSYML XTKAQXTS AT ZT IMEYAMS D IWVŠVDYOV MACKVOVLYZT ŽVC ŽVOACKČŽCVK ŠMSZOVWSTŠVD, ŽVC OTČLVKTO VEMIVDMSTQ OTPM, EKDY KMIYAŽVDMSTQ KYLAŽT QTACT YO ŠKČWYX WMSMŽAYZ. ŽVC LSMŠTOYR ZT YI KVŠOT OTLRYZT EVPTWOYS D MOWSYZV. D IMRTCŽČ ZT PYS WVŠPTOYŽ, ŽVLEVOYAC YO ČRYCTSZ WSMAPT, ŽMAOTZT EM ZT AEKTLTOYS EVŽSYQ YO EVACMS TŠTO OMZDTRZYX MACKVOVLVD. PYS ZT AMLVČŽ D WSMAPY YO D MACKVOVLYZY. WKMŠYS ZT DAT DTRZT ŠMSZOVWSTŠT, ŽY ZYX ZT EVBYSZMS OM DAT ACKMOY.",
u"YOSŠAGWY XŠ B BEOXWŽ RŠZOŽ ŽOQGO ESZWELZ GL EBO JGLGOBČ WG BSAŠŽŠGWZ QZOEŠYOE SOUZŠR GL BEŠČ. KWEŠZ WG DBČELAXLZ XŠ GL SAŠVORD WJ BAŠRGXŠUL EŠYL E GOEW EŠY, YO BO TŠERLZGO RADKMO SAŠČAŠBLZW SOŽŠŽMGW ROUORYW. JGLGXŠ LBČAOGOŽWXŠ XŠ MWZO GDXGO SOČAŠMGO SAW ČAUOELGXD GL ROZUWV ŽOABYWV SOČŠV. ŽWBŠZ O OYAOUZW JŠŽZXW XŠ SOBČLXLZL BSZOCGO JGLGL. EBŠŽD ČŠŽD XŠ BZŠRWZL CŠ  GOEL SAŠRBČLEL O JUALRMW EŠBOZXL. RO YOSŠAGWYL BO ŽWBZWZW, RL XŠ JŠŽZXL GŠSAŠŽWQGL, RL ZŠKW E BAŠRWCQD EŠBOZXBČEL WG RL BŠ EBŠ JEŠJRŠ, SZLGŠČW, BOGNŠ WG ZDGL UWMZXŠXO OYOZW GXŠ.",
u"WTFNQ XG OG M WGMŠN PRGDPN FWŽANŠN M LBXBMXPGR KWNCTMOŽ. PTZ RBZGRBZNPB JB ŠBOCTQO UTLŠBRT PTZ BMZTWOB ŠOGJTMNK QTJBWNZRTM, X PBZGWNRN XT WBDŽŠBQN UT XMGZŽ M LŠBŠTXZN, YTQXZMŽ NŠ MXBPFBŠOGR ANMQOGŠOŽ MXG FT RŠTANDŠG ŽUTWBCG GQGPZWTŠXPNK WBDŽŠBQŠNPTM. PTZ UWTHGXTW RBZGRBZNPG ŠB YTQN OG ŠBUNXBQ RBZGRBZNDŠB NŠ HNLNPBQŠB ŽDCGŠNPB. DGUWBM OG MGJB X XMTONRN QTJBWNZRN LBXQTMGQ UWGFMXGR PTZ RBZGRBZNP, OG CNQ MGDON FGQ ŠOGJTMNK WBLUWBM NŠ ŽDCGŠNPTM UTXMGDGŠNK HNLNPN. ŠOGJTMB FGQB M HNLNPN LBOGRBOT MXB UTFWTDOB RGKBŠNPG, UWGFMXGR ZGTWNOT JWBMNZBČNOG NŠ L ŠOT UTMGLBŠT BXZWTŠTRNOT.",
u"AOGBG H OSGJ NAYXFBAJ VGDČBG, H SLQGFBR HCHČA FBGFG HMA AF CLHWGFBR HCHČA MHFZX, MH AVLGCČA WG FGCXQGLA EAČHVHEA MQXLGNX SGCX. QG DAMČA MH RQHFAČG S IHVXYH. IHSVGČ BAJ BG CHIGLFAC, CA BG IHMQXSAČ MHFZG S MLGOAPŽG FXPGNX IČXFGQFGNX MAMQGDX, VGDČBH IX ILGDXCFAČ S SLMQH IČXFGQHS, CA MG NAYČBGBH HCHČA MHFZX. CHIGLFACHS FXRC BG IHDGFAČ ILGČHD M PQGSAČFADA QLXOAZABXDA AF OHQGOXFBAD MSGQHSFAD FXVHLHD. SGM MLGOFBGSGPCA MSGQ MG BG FXMČXFBXČ FX FGMILGDGFČBASHMQ HYMQHBGŽGNX LGOX. ČG OLVFA ČBROBG MH MA RIXČA AVLGŽA DAMGČ H NAYXFBR VGDČBG.",
u"VPSSPCŠ NIYZFNIS ZI QI ACWPZCS O AMUHUOPTU CZČYUTUŠPQI RUČ RUTZČYLRČUY HCSQTUMSIHUO, RUČ TILŠUYIT UWCAUOCSIF TIDC, WYOP YCAPZRUOCSIF YPŠZRI FIZČI PT HYLMPN MCSCRZPQ. RUČ ŠSCHITPG QI PA YUHTI TIŠGPQI WUDIMTPS O CTMSPQU. O ACGIČRL QI DPS MUHDITPR, RUŠWUTPZČ PT LGPČISQ MSCZDI, RCZTIQI WC QI ZWYIŠITPS WURSPF PT WUZČCS IHIT TCQOIGQPN CZČYUTUŠUO. DPS QI ZCŠULR O MSCZDP PT O CZČYUTUŠPQP. MYCHPS QI OZI OIGQI HCSQTUMSIHI, RP QPN QI WUŽPSQCS TC OZI ZČYCTP."]

random.seed("Random seed:)")
random.shuffle(hard)
texts = [easy, medium, hard, ready]
random.seed()


def crypt(text):
    xyz = [x for x in abc]
    random.shuffle(xyz)
    return ''.join([xyz[abc.index(x)] if x in abc else x for x in text.upper()])

@app.route("/")
def index():
    return "TODO"

@app.route("/<difficulty>")
@app.route("/<difficulty>/<int:idx>")
def play(difficulty, idx=-1):
    if (difficulty == "ready"):
        level = 3
    elif (difficulty == "hard"):
        level = 2
    elif (difficulty == "medium"):
        level = 1
    else:
        level = 0
    if idx < 0 and level == 3:
        return render_template("substitution.ready.html", num=len(ready))
    if idx < 0 or idx >= len(texts[level]):
        idx = random.randrange(len(texts[level]))
    text = texts[level][idx]
    if level == 2:
        text = re.sub(r'\s', '', text)
    if level == 3:
        cipher = text
    else:
        cipher = crypt(text)
    return render_template("substitution.play.html",
        nav = "substitution", next = (idx+1) % len(texts[level]),
        difficulty = difficulty, level = level, input = json.dumps(cipher),
        foreign = len(set(['Q', 'W', 'X', 'Y']).intersection(text.upper())) > 0)
    
